spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://helpdesk-user:helpdesk-user@clusterhelpdesk.leyoy.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true

springdoc:
  openapi:
    title: 'User Service API'
    description: 'Component responsible for user management created on Formacao Backend'
    version: '1.0.0'